### PR TITLE
add lab4_v2

### PR DESCRIPTION
**Pull request by artykisa**
fix a lot of added files

### CODE REVIEW

**Comment by artykisa** [comment]
Same link https://artykisa.github.io/Frontend-Tasks/Lab4/html/main.html

**Comment by artykisa** [comment]
Previous pr https://github.com/artykisa/Frontend-Tasks/pull/4

**Comment by artykisa** [comment]
So you can find tracks and lyrics for them in search input. You can try something like "Kendrick Lamar", "Lyapis Trubetskoy" or "GONE Fludd". Also you can add your own after login in your profile.

**Review by gmltA — COMMENTED** [review]
This is fine, but your implementation of lyrics explanation does not follow the requirements.

I can offer you <kbd>6</kbd> after you fix this thing.

**Comment by artykisa** [comment]
So now u can click on line in lyrics and write explanation near the line, after u change focus from this input explanation will be updated

**Comment by artykisa** [comment]
New link
https://artykisa.github.io/KisurinGeniusHost/html/main

**Comment by artykisa** [comment]
And also can u accept github-pages as 5th lab?

**Review by gmltA — COMMENTED** [review]
Okay. Now that's a <kbd>6</kbd>. Will that be enough?

**Comment by gmltA** [comment]
> And also can u accept github-pages as 5th lab?

I will.

**Comment by artykisa** [comment]
Yeah, thats enough, thank you

**Comment by artykisa** [comment]
Can you approve?

**Review by gmltA — APPROVED** [review]

**Pull request merged**
