### PR TITLE
design reference

### PR DESCRIPTION
**Pull request by artykisa**
15. Song and lyrics DB

### CODE REVIEW

**Comment by artykisa** [comment]
https://wireframepro.mockflow.com/view/M1867551e85b13e4463cbdcf0d12ec8af1616331967124

**Review by gmltA — CHANGES_REQUESTED** [review]
**Main page** – `nav` has wrong content. Either replace it with a different tag, or re-think what should be inside.
**Track page** – I'm pretty sure you can find a place for `article` tag there.

And you are missing some required functions: rating, song lyrics selector (when there are more than one), controls of how to add a comment to the lyrics and so on.

Also mobile version's header should be reworked (consider hamburger menu) because of lack of free space.

**Comment by artykisa** [comment]
I have fixed my design, so u can review it by the same reference

**Review by gmltA — COMMENTED** [review]
That's better.
I can let you go with <kbd>8</kbd> now. Tell me if you are willing to improve it.

**Comment by artykisa** [comment]
I'm ok with 8, thank you

**Comment by artykisa** [comment]
Can u approve my pr, please?

**Review by gmltA — APPROVED** [review]

**Pull request merged**
